/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.

API version: 2.0.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the WarpShip200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WarpShip200ResponseData{}

// WarpShip200ResponseData struct for WarpShip200ResponseData
type WarpShip200ResponseData struct {
	Fuel                 ShipFuel `json:"fuel"`
	Nav                  ShipNav  `json:"nav"`
	AdditionalProperties map[string]interface{}
}

type _WarpShip200ResponseData WarpShip200ResponseData

// NewWarpShip200ResponseData instantiates a new WarpShip200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWarpShip200ResponseData(fuel ShipFuel, nav ShipNav) *WarpShip200ResponseData {
	this := WarpShip200ResponseData{}
	this.Fuel = fuel
	this.Nav = nav
	return &this
}

// NewWarpShip200ResponseDataWithDefaults instantiates a new WarpShip200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWarpShip200ResponseDataWithDefaults() *WarpShip200ResponseData {
	this := WarpShip200ResponseData{}
	return &this
}

// GetFuel returns the Fuel field value
func (o *WarpShip200ResponseData) GetFuel() ShipFuel {
	if o == nil {
		var ret ShipFuel
		return ret
	}

	return o.Fuel
}

// GetFuelOk returns a tuple with the Fuel field value
// and a boolean to check if the value has been set.
func (o *WarpShip200ResponseData) GetFuelOk() (*ShipFuel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fuel, true
}

// SetFuel sets field value
func (o *WarpShip200ResponseData) SetFuel(v ShipFuel) {
	o.Fuel = v
}

// GetNav returns the Nav field value
func (o *WarpShip200ResponseData) GetNav() ShipNav {
	if o == nil {
		var ret ShipNav
		return ret
	}

	return o.Nav
}

// GetNavOk returns a tuple with the Nav field value
// and a boolean to check if the value has been set.
func (o *WarpShip200ResponseData) GetNavOk() (*ShipNav, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nav, true
}

// SetNav sets field value
func (o *WarpShip200ResponseData) SetNav(v ShipNav) {
	o.Nav = v
}

func (o WarpShip200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WarpShip200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fuel"] = o.Fuel
	toSerialize["nav"] = o.Nav

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WarpShip200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fuel",
		"nav",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWarpShip200ResponseData := _WarpShip200ResponseData{}

	err = json.Unmarshal(data, &varWarpShip200ResponseData)

	if err != nil {
		return err
	}

	*o = WarpShip200ResponseData(varWarpShip200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fuel")
		delete(additionalProperties, "nav")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWarpShip200ResponseData struct {
	value *WarpShip200ResponseData
	isSet bool
}

func (v NullableWarpShip200ResponseData) Get() *WarpShip200ResponseData {
	return v.value
}

func (v *NullableWarpShip200ResponseData) Set(val *WarpShip200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableWarpShip200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableWarpShip200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWarpShip200ResponseData(val *WarpShip200ResponseData) *NullableWarpShip200ResponseData {
	return &NullableWarpShip200ResponseData{value: val, isSet: true}
}

func (v NullableWarpShip200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWarpShip200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
